/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import datos.ClsEmpleadoJDBC;
import dominio.ClsEmpleado;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import views.*;

/**
 *
 * @author Joe
 */
public class Menu extends javax.swing.JFrame {

    /*VISTAS*/
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setModelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        BtnElimar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnCrear.setBackground(new java.awt.Color(0, 153, 51));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 102, 204));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        BtnElimar.setBackground(new java.awt.Color(255, 51, 51));
        BtnElimar.setForeground(new java.awt.Color(255, 255, 255));
        BtnElimar.setText("Eliminar");
        BtnElimar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnElimarMouseClicked(evt);
            }
        });
        BtnElimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnElimar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnElimar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tbEmpleados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        Login vLogin = new Login();
        vLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private DefaultTableModel baseTabla = new DefaultTableModel();
    
    private void setModelo () {
        String[] cabecera = {"Cod.","Nombre empleado", "Enero", "Febrero", "Marzo","Total", "Promedio"};
        baseTabla.setColumnIdentifiers(cabecera);
        this.tbEmpleados.setModel(baseTabla);
    }
    public void agregarNuevo() {        
        ClsEmpleadoJDBC tbEmpleado = new ClsEmpleadoJDBC();        
        ClsEmpleado nuevo = tbEmpleado.obtenerUltimo();
        
        Object[] fila = new Object[7];
        fila[0] = nuevo.getIdemple();
        fila[1] = nuevo.getEmpleado();
        fila[2] = nuevo.getEnero();
        fila[3] = nuevo.getFebrero();
        fila[4] = nuevo.getMarzo();
        fila[5] = nuevo.getTotal();
        fila[6] = nuevo.getPromedio();             
        this.baseTabla.addRow(fila);
        this.tbEmpleados.setModel(baseTabla);
    }
    
    private void setDatos() {
        ClsEmpleadoJDBC alJDBC = new ClsEmpleadoJDBC();
        List<ClsEmpleado> dataTabla = alJDBC.seleccion();
        Object[] fila = new Object[7];
        
        for (ClsEmpleado emple : dataTabla){
            fila[0] = emple.getIdemple();
            fila[1] = emple.getEmpleado();
            fila[2] = emple.getEnero();
            fila[3] = emple.getFebrero();
            fila[4] = emple.getMarzo();
            fila[5] = emple.getTotal();
            fila[6] = emple.getPromedio(); 
            
            System.out.println("Empleado="+emple);
            this.baseTabla.addRow(fila);
        }
        this.tbEmpleados.setModel(baseTabla);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setDatos();       
    }//GEN-LAST:event_formWindowOpened

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        Formulario form = new Formulario(this, true);
        form.setVisible(true);
    }//GEN-LAST:event_btnCrearMouseClicked

    private ClsEmpleado empleadoMod;
    private int filaEdit;
    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        this.empleadoMod = new ClsEmpleado();
        int fila = this.tbEmpleados.getSelectedRow();
        filaEdit = fila;
        if(fila >= 0){
            String idEmple = this.tbEmpleados.getValueAt(fila, 0).toString();
            String empleado = this.tbEmpleados.getValueAt(fila, 1).toString();
            String enero =  this.tbEmpleados.getValueAt(fila, 2).toString();
            String febrero = this.tbEmpleados.getValueAt(fila, 3).toString();
            String marzo = this.tbEmpleados.getValueAt(fila, 4).toString();
            try {
                this.empleadoMod.setIdemple(Integer.parseInt(idEmple));
                this.empleadoMod.setEmpleado(empleado);
                this.empleadoMod.setEnero(Integer.parseInt(enero));
                this.empleadoMod.setFebrero(Integer.parseInt(febrero));
                this.empleadoMod.setMarzo(Integer.parseInt(marzo)); 
            }catch(Exception e){
                System.out.println("Datos no validos: "+e);
            }
            if(empleadoMod.datosMinimosLlenos()){ 
                FormularioActualizar fActualizar = new FormularioActualizar(this, true, empleadoMod);
                fActualizar.setVisible(true);
            }   
        }else{
            System.out.println(fila);
        }
    }//GEN-LAST:event_btnActualizarMouseClicked
        
    public void actualizarFila(ClsEmpleado empleActualizado) {
        Object[] fila = new Object[7];
        fila[0] = empleActualizado.getIdemple();
        fila[1] = empleActualizado.getEmpleado();
        fila[2] = empleActualizado.getEnero();
        fila[3] = empleActualizado.getFebrero();
        fila[4] = empleActualizado.getMarzo();
        fila[5] = empleActualizado.getTotal();
        fila[6] = empleActualizado.getPromedio();             
        this.baseTabla.setValueAt(fila[0], filaEdit, 0);     
        this.baseTabla.setValueAt(fila[1], filaEdit, 1);     
        this.baseTabla.setValueAt(fila[2], filaEdit, 2);     
        this.baseTabla.setValueAt(fila[3], filaEdit, 3);     
        this.baseTabla.setValueAt(fila[4], filaEdit, 4);     
        this.baseTabla.setValueAt(fila[5], filaEdit, 5);     
        this.baseTabla.setValueAt(fila[6], filaEdit, 6);
        this.tbEmpleados.setModel(baseTabla);
    }
    
    private void BtnElimarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnElimarMouseClicked
        this.empleadoMod = new ClsEmpleado();
        int fila = this.tbEmpleados.getSelectedRow();
        filaEdit = fila;
        if(fila >= 0){
            String idEmple = this.tbEmpleados.getValueAt(fila, 0).toString();
            String empleado = this.tbEmpleados.getValueAt(fila, 1).toString();
            String enero =  this.tbEmpleados.getValueAt(fila, 2).toString();
            String febrero = this.tbEmpleados.getValueAt(fila, 3).toString();
            String marzo = this.tbEmpleados.getValueAt(fila, 4).toString();
            try {
                this.empleadoMod.setIdemple(Integer.parseInt(idEmple));
                this.empleadoMod.setEmpleado(empleado);
                this.empleadoMod.setEnero(Integer.parseInt(enero));
                this.empleadoMod.setFebrero(Integer.parseInt(febrero));
                this.empleadoMod.setMarzo(Integer.parseInt(marzo)); 
            }catch(Exception e){
                System.out.println("Datos no validos: "+e);
            }
            if(empleadoMod.datosMinimosLlenos()){ 
                ConfirmarEliminar jdEliminar = 
                        new ConfirmarEliminar(
                            this, 
                            true, 
                            this.empleadoMod.getIdemple(), 
                            this.empleadoMod.getEmpleado()
                        );
                jdEliminar.setVisible(true);
            }   
        }else{
            System.out.println(fila);
        }
    }//GEN-LAST:event_BtnElimarMouseClicked

    private void BtnElimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnElimarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed
    
    public void limpiarFila(ConfirmarEliminar jdEliminar){
        this.baseTabla.removeRow(filaEdit);
        setTimeout(() -> jdEliminar.dispose(), 800);
    }

    public static void setTimeout(Runnable runnable, int delay){
        new Thread(() -> {
            try {
                Thread.sleep(delay);
                runnable.run();
            }
            catch (Exception e){
                System.err.println(e);
            }
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnElimar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmpleados;
    // End of variables declaration//GEN-END:variables

}
